-- Copyright (c) 2026 Evolve Quant LLC. All rights reserved.
-- Source-available for evaluation under the LICENSE file.
CREATE DATABASE IF NOT EXISTS eth_research
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE eth_research;

CREATE TABLE IF NOT EXISTS ohlcv_features_1m (
  `timestamp` DATETIME NOT NULL,
  `unix` DOUBLE NULL,
  `open` DOUBLE NULL,
  `high` DOUBLE NULL,
  `low` DOUBLE NULL,
  `close` DOUBLE NULL,
  `vwap` DOUBLE NULL,
  `ETH_volume` DOUBLE NULL,
  `USD_volume` DOUBLE NULL,
  `moving_average` DOUBLE NULL,
  `slope` DOUBLE NULL,
  `VWAP_slope` DOUBLE NULL,
  `ma_13` DOUBLE NULL,
  `ma_slope_13` DOUBLE NULL,
  `ma_slope_of_slope_13` DOUBLE NULL,
  `ma_slope_norm_13` DOUBLE NULL,
  `ma_slope_of_slope_norm_13` DOUBLE NULL,
  `vwap_13` DOUBLE NULL,
  `vwap_slope_13` DOUBLE NULL,
  `vwap_slope_of_slope_13` DOUBLE NULL,
  `vwap_slope_norm_13` DOUBLE NULL,
  `vwap_slope_of_slope_norm_13` DOUBLE NULL,
  `ma_21` DOUBLE NULL,
  `ma_slope_21` DOUBLE NULL,
  `ma_slope_of_slope_21` DOUBLE NULL,
  `ma_slope_norm_21` DOUBLE NULL,
  `ma_slope_of_slope_norm_21` DOUBLE NULL,
  `vwap_21` DOUBLE NULL,
  `vwap_slope_21` DOUBLE NULL,
  `vwap_slope_of_slope_21` DOUBLE NULL,
  `vwap_slope_norm_21` DOUBLE NULL,
  `vwap_slope_of_slope_norm_21` DOUBLE NULL,
  `ma_50` DOUBLE NULL,
  `ma_slope_50` DOUBLE NULL,
  `ma_slope_of_slope_50` DOUBLE NULL,
  `ma_slope_norm_50` DOUBLE NULL,
  `ma_slope_of_slope_norm_50` DOUBLE NULL,
  `vwap_50` DOUBLE NULL,
  `vwap_slope_50` DOUBLE NULL,
  `vwap_slope_of_slope_50` DOUBLE NULL,
  `vwap_slope_norm_50` DOUBLE NULL,
  `vwap_slope_of_slope_norm_50` DOUBLE NULL,
  `ma_100` DOUBLE NULL,
  `ma_slope_100` DOUBLE NULL,
  `ma_slope_of_slope_100` DOUBLE NULL,
  `ma_slope_norm_100` DOUBLE NULL,
  `ma_slope_of_slope_norm_100` DOUBLE NULL,
  `vwap_100` DOUBLE NULL,
  `vwap_slope_100` DOUBLE NULL,
  `vwap_slope_of_slope_100` DOUBLE NULL,
  `vwap_slope_norm_100` DOUBLE NULL,
  `vwap_slope_of_slope_norm_100` DOUBLE NULL,
  `ma_200` DOUBLE NULL,
  `ma_slope_200` DOUBLE NULL,
  `ma_slope_of_slope_200` DOUBLE NULL,
  `ma_slope_norm_200` DOUBLE NULL,
  `ma_slope_of_slope_norm_200` DOUBLE NULL,
  `vwap_200` DOUBLE NULL,
  `vwap_slope_200` DOUBLE NULL,
  `vwap_slope_of_slope_200` DOUBLE NULL,
  `vwap_slope_norm_200` DOUBLE NULL,
  `vwap_slope_of_slope_norm_200` DOUBLE NULL,
  PRIMARY KEY (`timestamp`),
  INDEX idx_timestamp (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

